Afghanistan = "AFG"
Albania = "ALB"
Algeria = "DZA"
"American Samoa" = "ASM"
Andorra = "AND"
Angola = "AGO"
Anguilla = "AIA"
Antarctica = "ATA"
"Antigua and Barbuda" = "ATG"
"Arctic Ocean" = nan
Argentina = "ARG"
Armenia = "ARM"
Aruba = "ABW"
"Ashmore and Cartier Islands" = nan
"Atlantic Ocean" = nan
Australia = "AUS"
Austria = "AUT"
Azerbaijan = "AZE"
Bahamas = "BHS"
Bahrain = "BHR"
"Baltic Sea" = nan
"Baker Island" = nan
Bangladesh = "BGD"
Barbados = "BRB"
"Bassas da India" = nan
Belarus = "BLR"
Belgium = "BEL"
Belize = "BLZ"
Benin = "BEN"
Bermuda = "BMU"
Bhutan = "BTN"
Bolivia = "BOL"
Borneo = nan
"Bosnia and Herzegovina" = "BIH"
Botswana = "BWA"
"Bouvet Island" = "BVT"
Brazil = "BRA"
"British Virgin Islands" = "VGB"
Brunei = "BRN"
Bulgaria = "BGR"
"Burkina Faso" = "BFA"
Burundi = "BDI"
Cambodia = "KHM"
Cameroon = "CMR"
Canada = "CAN"
"Cape Verde" = "CPV"
"Cayman Islands" = "CYM"
"Central African Republic" = "CAF"
Chad = "TCD"
Chile = "CHL"
China = "CHN"
"Christmas Island" = "CXR"
"Clipperton Island" = nan
"Cocos Islands" = "CCK"
Colombia = "COL"
Comoros = "COM"
"Cook Islands" = "COK"
"Coral Sea Islands" = nan
"Costa Rica" = "CRI"
"Cote d’Ivoire" = "CIV"
Croatia = "HRV"
Cuba = "CUB"
Curacao = "CUW"
Cyprus = "CYP"
Czechia = "CZE"
"Democratic Republic of the Congo" = "COD"
Denmark = "DNK"
Djibouti = "DJI"
Dominica = "DMA"
"Dominican Republic" = "DOM"
Ecuador = "ECU"
Egypt = "EGY"
"El Salvador" = "SLV"
"Equatorial Guinea" = "GNQ"
Eritrea = "ERI"
Estonia = "EST"
Eswatini = "SWZ"
Ethiopia = "ETH"
"Europa Island" = nan
"Falkland Islands (Islas Malvinas)" = "FLK"
"Faroe Islands" = "FRO"
Fiji = "FJI"
Finland = "FIN"
France = "FRA"
"French Guiana" = "GUF"
"French Polynesia" = "PYF"
"French Southern and Antarctic Lands" = nan
Gabon = "GAB"
Gambia = "GMB"
"Gaza Strip" = "PSE"
Georgia = "GEO"
Germany = "DEU"
Ghana = "GHA"
Gibraltar = "GIB"
"Glorioso Islands" = nan
Greece = "GRC"
Greenland = "GRL"
Grenada = "GRD"
Guadeloupe = "GLP"
Guam = "GUM"
Guatemala = "GTM"
Guernsey = "GGY"
Guinea = "GIN"
Guinea-Bissau = "GNB"
Guyana = "GUY"
Haiti = "HTI"
"Heard Island and McDonald Islands" = "HMD"
Honduras = "HND"
"Hong Kong" = "HKG"
"Howland Island" = nan
Hungary = "HUN"
Iceland = "ISL"
India = "IND"
"Indian Ocean" = nan
Indonesia = "IDN"
Iran = "IRN"
Iraq = "IRQ"
Ireland = "IRL"
"Isle of Man" = "IMN"
Israel = "ISR"
Italy = "ITA"
Jamaica = "JAM"
"Jan Mayen" = nan
Japan = "JPN"
"Jarvis Island" = nan
Jersey = "JEY"
"Johnston Atoll" = nan
Jordan = "JOR"
"Juan de Nova Island" = nan
Kazakhstan = "KAZ"
Kenya = "KEN"
"Kerguelen Archipelago" = nan
"Kingman Reef" = nan
Kiribati = "KIR"
Kosovo = "XKX"
Kuwait = "KWT"
Kyrgyzstan = "KGZ"
Laos = "LAO"
Latvia = "LVA"
Lebanon = "LBN"
Lesotho = "LSO"
Liberia = "LBR"
Libya = "LBY"
Liechtenstein = "LIE"
"Line Islands" = nan
Lithuania = "LTU"
Luxembourg = "LUX"
Macau = "MAC"
Madagascar = "MDG"
Malawi = "MWI"
Malaysia = "MYS"
Maldives = "MDV"
Mali = "MLI"
Malta = "MLT"
"Marshall Islands" = "MHL"
Martinique = "MTQ"
Mauritania = "MRT"
Mauritius = "MUS"
Mayotte = "MYT"
"Mediterranean Sea" = nan
Mexico = "MEX"
"Micronesia, Federated States of" = nan
"Midway Islands" = nan
Moldova = "MDA"
Monaco = "MCO"
Mongolia = "MNG"
Montenegro = "MNE"
Montserrat = "MSR"
Morocco = "MAR"
Mozambique = "MOZ"
Myanmar = "MMR"
Namibia = "NAM"
Nauru = "NRU"
"Navassa Island" = nan
Nepal = "NPL"
Netherlands = "NLD"
"New Caledonia" = "NCL"
"New Zealand" = "NZL"
Nicaragua = "NIC"
Niger = "NER"
Nigeria = "NGA"
Niue = "NIU"
"Norfolk Island" = "NFK"
"North Korea" = "PRK"
"North Macedonia" = "MKD"
"North Sea" = nan
"Northern Mariana Islands" = "MNP"
Norway = "NOR"
Oman = "OMN"
"Pacific Ocean" = nan
Pakistan = "PAK"
Palau = "PLW"
"Palmyra Atoll" = nan
Panama = "PAN"
"Papua New Guinea" = "PNG"
"Paracel Islands" = nan
Paraguay = "PRY"
Peru = "PER"
Philippines = "PHL"
"Pitcairn Islands" = nan
Poland = "POL"
Portugal = "PRT"
"Puerto Rico" = "PRI"
Qatar = "QAT"
"Republic of the Congo" = "COG"
Reunion = nan
Romania = "ROU"
"Ross Sea" = nan
Russia = "RUS"
Rwanda = "RWA"
"Saint Barthelemy" = nan
"Saint Helena" = "SHN"
"Saint Kitts and Nevis" = "KNA"
"Saint Lucia" = "LCA"
"Saint Martin" = nan
"Saint Pierre and Miquelon" = "SPM"
"Saint Vincent and the Grenadines" = "VCT"
Samoa = "WSM"
"San Marino" = "SMR"
"Sao Tome and Principe" = "STP"
"Saudi Arabia" = "SAU"
Senegal = "SEN"
Serbia = "SRB"
Seychelles = "SYC"
"Sierra Leone" = "SLE"
Singapore = "SGP"
"Sint Maarten" = nan
Slovakia = "SVK"
Slovenia = "SVN"
"Solomon Islands" = "SLB"
Somalia = "SOM"
"South Africa" = "ZAF"
"South Georgia and the South Sandwich Islands" = "SGS"
"South Korea" = "KOR"
"South Sudan" = "SSD"
"Southern Ocean" = nan
Spain = "ESP"
"Spratly Islands" = nan
"Sri Lanka" = "LKA"
"State of Palestine" = "PSE"
Sudan = "SDN"
Suriname = "SUR"
Svalbard = "SJM"
Sweden = "SWE"
Switzerland = "CHE"
Syria = "SYR"
Taiwan = "TWN"
Tajikistan = "TJK"
Tanzania = "TZA"
"Tasman Sea" = nan
Thailand = "THA"
Timor-Leste = "TLS"
Togo = "TGO"
Tokelau = "TKL"
Tonga = "TON"
"Trinidad and Tobago" = "TTO"
"Tromelin Island" = nan
Tunisia = "TUN"
Turkey = "TUR"
Turkmenistan = "TKM"
"Turks and Caicos Islands" = "TCA"
Tuvalu = "TUV"
Uganda = "UGA"
Ukraine = "UKR"
"United Arab Emirates" = "ARE"
"United Kingdom" = "GBR"
Uruguay = "URY"
USA = "USA"
Uzbekistan = "UZB"
Vanuatu = "VUT"
Venezuela = "VEN"
"Viet Nam" = "VNM"
"Virgin Islands" = "VIR"
"Wake Island" = nan
"Wallis and Futuna" = "WLF"
"West Bank" = "PSE"
"Western Sahara" = "ESH"
Yemen = "YEM"
Zambia = "ZMB"
Zimbabwe = "ZWE"
"missing: control sample" = nan
"missing: data agreement established pre-2023" = nan
"missing: endangered species" = nan
"missing: human-identifiable" = nan
"missing: lab stock" = nan
"missing: sample group" = nan
"missing: synthetic construct" = nan
"missing: third party data" = nan
"not applicable " = nan